# Generated by Django 5.2.4 on 2025-08-24 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        ('products_and_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_chart', to='charts.chartitem'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_chart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_items', to='charts.chart'),
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_item', to='products_and_categories.product'),
        ),
    ]
