# Generated by Django 5.2.4 on 2025-08-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chart_items_alter_chart_user_alter_chartitem_chart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='items',
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='charts.chart'),
        ),
    ]
