# Generated by Django 5.2.4 on 2025-09-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_paystack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
