# Generated by Django 5.2.4 on 2025-09-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_paystack', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
