# Generated by Django 5.2.4 on 2025-09-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_paystack', '0005_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
